server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: rabbit_ai
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

jwt:
  secret: your-secret-key
  expire_hours: 24

aliyun:
  access_key_id: your-access-key-id
  access_key_secret: your-access-key-secret
  region: cn-hangzhou
  one_click_app_id: your-app-id

github:
  client_id: your-github-client-id
  client_secret: your-github-client-secret
  redirect_url: http://localhost:8080/api/v1/auth/github/callback

minimax:
  api_key: your-minimax-api-key
  base_url: https://api.minimaxi.com/v1
